#  1a. Numpy exercises

1. Import the numpy package under the name `np`

`hint: import … as`

In [1]:
import numpy as np

2. Create a null vector of size 10

`hint: np.zeros`



In [2]:
zeros = np.zeros((10,))
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 0 to 100

`hint: arange`

In [3]:
range = np.arange(101)
print(range)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


4. Create a 10x10 matrix with random values and find the minimum, maximum, and mean values. Normalize the said matrix

`hint: min, max, ...`

In [4]:
matrix = np.random.rand(10, 10)

minimum_value = np.min(matrix)
maximum_value = np.max(matrix)
mean_value = np.mean(matrix)

# Normalization by: (value - min values of matrix) / (max value of matrix - min value of matrix)
norm_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))

print("Minimum value:", minimum_value)
print("Maximum value:", maximum_value)
print("Mean value:", mean_value)
print("Normalized matrix:")
print(norm_matrix)

Minimum value: 0.0010948719094959758
Maximum value: 0.9933673815401622
Mean value: 0.4687449146385616
Normalized matrix:
[[1.         0.34144321 0.6390645  0.49638795 0.2768261  0.39426736
  0.95173356 0.06615867 0.10716268 0.866347  ]
 [0.03157601 0.72398493 0.80134941 0.46508358 0.28528071 0.09475598
  0.53784628 0.70214652 0.90113247 0.68806095]
 [0.24212062 0.45118037 0.14499086 0.24257801 0.15374122 0.40328102
  0.2336626  0.05940454 0.76111019 0.74513804]
 [0.55344142 0.41804192 0.41039729 0.20113445 0.37351471 0.18482418
  0.54666993 0.07425401 0.31204196 0.2775712 ]
 [0.25451991 0.93619671 0.63292227 0.70300606 0.83246751 0.72537871
  0.         0.96852473 0.89868609 0.61221393]
 [0.77082699 0.6321348  0.0541309  0.66597018 0.49795863 0.27278253
  0.57938531 0.72698353 0.89843901 0.43823632]
 [0.38331192 0.71414395 0.4447604  0.58499621 0.66907896 0.19752411
  0.16115866 0.34473279 0.13144687 0.20155635]
 [0.48363226 0.58327197 0.56653813 0.12012827 0.57164447 0.5475967
  0.667

5. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

`hint: np.sqrt, np.arctan2`

In [5]:
# Create a random 10x2 matrix representing Cartesian coordinates
cartesian_matrix = np.random.rand(10, 2)

# Convert to polar coordinates
x = cartesian_matrix[:, 0]
y = cartesian_matrix[:, 1]
r = np.sqrt(x**2 + y**2)  # Calculate the distance from the origin (radius)
theta = np.arctan2(y, x)  # Calculate the angle from the x-axis (theta)

# Create a new 10x2 matrix representing polar coordinates
polar_matrix = np.column_stack((r, theta))

# Print the original Cartesian matrix and the converted polar matrix
print("Cartesian coordinates:")
print(cartesian_matrix)
print("\nPolar coordinates:")
print(polar_matrix)

Cartesian coordinates:
[[0.24194856 0.17426054]
 [0.93566132 0.54442099]
 [0.66371053 0.33883933]
 [0.53002597 0.03793061]
 [0.65340395 0.17773648]
 [0.29680931 0.88592292]
 [0.9439264  0.50297506]
 [0.11505083 0.6537269 ]
 [0.92790375 0.21792943]
 [0.23532575 0.50092938]]

Polar coordinates:
[[0.29817083 0.62417978]
 [1.08252313 0.52697215]
 [0.74520048 0.47203034]
 [0.53138146 0.0714419 ]
 [0.6771462  0.26559012]
 [0.93432071 1.24752101]
 [1.06957045 0.48958415]
 [0.66377372 1.39658811]
 [0.95315193 0.23068128]
 [0.5534514  1.13161705]]


6. Create random vector of size 10 and replace the maximum value by 0

`hint: argmax`

In [10]:
z = np.random.rand(10)
print(z)

[0.32160283 0.16213045 0.56109666 0.91307065 0.29724046 0.6730942
 0.10586118 0.30382319 0.94377915 0.77541779]


In [11]:
z[z == np.max(z)] = 0
print(z)

[0.32160283 0.16213045 0.56109666 0.91307065 0.29724046 0.6730942
 0.10586118 0.30382319 0.         0.77541779]


7. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

`hint: np.meshgrid`

In [24]:
x = np.arange(0, 1.1, 0.1)
print(x)
y = np.arange(0, 1.1, 0.1)
print(y)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [26]:
# Create a structured array with x and y coordinates
X, Y = np.meshgrid(x, y)

# Stack 1-D arrays as columns into a 2-D array.
structured_array = np.column_stack((X.ravel(), Y.ravel()))

structured_array

array([[0. , 0. ],
       [0.1, 0. ],
       [0.2, 0. ],
       [0.3, 0. ],
       [0.4, 0. ],
       [0.5, 0. ],
       [0.6, 0. ],
       [0.7, 0. ],
       [0.8, 0. ],
       [0.9, 0. ],
       [1. , 0. ],
       [0. , 0.1],
       [0.1, 0.1],
       [0.2, 0.1],
       [0.3, 0.1],
       [0.4, 0.1],
       [0.5, 0.1],
       [0.6, 0.1],
       [0.7, 0.1],
       [0.8, 0.1],
       [0.9, 0.1],
       [1. , 0.1],
       [0. , 0.2],
       [0.1, 0.2],
       [0.2, 0.2],
       [0.3, 0.2],
       [0.4, 0.2],
       [0.5, 0.2],
       [0.6, 0.2],
       [0.7, 0.2],
       [0.8, 0.2],
       [0.9, 0.2],
       [1. , 0.2],
       [0. , 0.3],
       [0.1, 0.3],
       [0.2, 0.3],
       [0.3, 0.3],
       [0.4, 0.3],
       [0.5, 0.3],
       [0.6, 0.3],
       [0.7, 0.3],
       [0.8, 0.3],
       [0.9, 0.3],
       [1. , 0.3],
       [0. , 0.4],
       [0.1, 0.4],
       [0.2, 0.4],
       [0.3, 0.4],
       [0.4, 0.4],
       [0.5, 0.4],
       [0.6, 0.4],
       [0.7, 0.4],
       [0.8,

8. Having a scalar `x` and a random vector `v`, find a value in `v` that is closest to `x`

`hint: argmin`

In [27]:
v = np.random.rand(10)
x = np.random.rand()
closest_value = v[np.abs(v-x).argmin()]
print("From", v, "to", x, "the closest value is", closest_value)

From [0.56975156 0.22962203 0.78708437 0.46793003 0.94846656 0.85952067
 0.38510286 0.50959084 0.21642068 0.69222958] to 0.048294854386137676 the closest value is 0.21642068212064813


9. Consider a random vector with shape (100,2) representing coordinates, find point by point distances and put them in a (100,100) array.

In [28]:
vector = np.random.rand(100,2)
print(vector)

[[0.72112796 0.06870975]
 [0.52273139 0.83932965]
 [0.73810104 0.94031041]
 [0.18000796 0.82721542]
 [0.19019841 0.58029056]
 [0.02914256 0.81781347]
 [0.00318543 0.98321901]
 [0.61730309 0.86495381]
 [0.01352132 0.14764027]
 [0.67755919 0.80408193]
 [0.4545183  0.52927052]
 [0.3665821  0.58024149]
 [0.93685159 0.72981317]
 [0.21265192 0.87101172]
 [0.24749489 0.77469282]
 [0.13442936 0.12945069]
 [0.93746811 0.28563673]
 [0.24262815 0.7700799 ]
 [0.04943438 0.30717228]
 [0.07767322 0.82095905]
 [0.00517948 0.78315392]
 [0.48398668 0.27365919]
 [0.91237915 0.15190767]
 [0.30805551 0.71310196]
 [0.29261909 0.47922802]
 [0.68486039 0.48949732]
 [0.72827596 0.29613477]
 [0.93534752 0.92472015]
 [0.69767474 0.50742738]
 [0.89146152 0.04141336]
 [0.36476056 0.83762759]
 [0.89160342 0.58092951]
 [0.58597305 0.29087826]
 [0.72067898 0.32156685]
 [0.03806422 0.53836574]
 [0.52132788 0.10939237]
 [0.87998624 0.03533684]
 [0.97910949 0.33448421]
 [0.08269626 0.59875663]
 [0.21750083 0.90802946]


In [33]:
# View inputs as arrays with at least two dimensions
x, y = np.atleast_2d(vector[:,0], vector[:,1])

# Calculate point-by-point distances: squared euclidean distance
d = np.sqrt((x-x.T)**2 + (y-y.T)**2)

print(vector.shape)
print(d)

(100, 2)
[[0.         0.79574885 0.87176591 ... 0.64359309 0.74058483 0.17890217]
 [0.79574885 0.         0.23786803 ... 0.70215199 0.43872067 0.62020153]
 [0.87176591 0.23786803 0.         ... 0.91762939 0.27600895 0.71420548]
 ...
 [0.64359309 0.70215199 0.91762939 ... 0.         0.98256654 0.5389352 ]
 [0.74058483 0.43872067 0.27600895 ... 0.98256654 0.         0.62114959]
 [0.17890217 0.62020153 0.71420548 ... 0.5389352  0.62114959 0.        ]]


10. Create a random (100, 100) matrix with values from 0 to 1. Turn all values lower than 0.5 into 0.0

In [18]:
vector = np.random.rand(100,100)
print(vector)

vector[vector < 0.5] = 0
print(vector)

[[0.08074307 0.24260747 0.3262154  ... 0.71698766 0.99598509 0.71529856]
 [0.46559758 0.2558712  0.95135087 ... 0.67487787 0.14501015 0.80956058]
 [0.22915168 0.0987818  0.15851576 ... 0.75700815 0.89365398 0.66866802]
 ...
 [0.20823558 0.14257344 0.11450439 ... 0.0264447  0.26705254 0.35251347]
 [0.25981747 0.52877396 0.95769164 ... 0.19400957 0.89051023 0.22806646]
 [0.77891208 0.98256827 0.28586012 ... 0.92421876 0.19381074 0.7456423 ]]
[[0.         0.         0.         ... 0.71698766 0.99598509 0.71529856]
 [0.         0.         0.95135087 ... 0.67487787 0.         0.80956058]
 [0.         0.         0.         ... 0.75700815 0.89365398 0.66866802]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.52877396 0.95769164 ... 0.         0.89051023 0.        ]
 [0.77891208 0.98256827 0.         ... 0.92421876 0.         0.7456423 ]]


11. Do a dot product of two matrices and print only the diagonal values.

In [19]:
matrix1 = np.random.rand(10,10)
matrix2 = np.random.rand(10,10)
dot_product = np.dot(matrix1, matrix2)
print(np.diagonal(dot_product))

[1.51010308 2.39339654 2.21037915 2.24804489 3.04143237 1.7961645
 2.52408673 1.56398922 2.90839926 2.67884869]


12. Swap two rows of a matrix.

In [20]:
matrix3 = np.random.rand(10,10)
print("Original matrix:")
print(matrix3)

matrix3[[0, 1]] = matrix3[[1, 0]]

print("Matrix after swapping rows:")
print(matrix3)

Original matrix:
[[0.69447953 0.04959939 0.17704192 0.55848788 0.92407621 0.22627967
  0.75103021 0.33358075 0.95365809 0.03027638]
 [0.77938885 0.30081672 0.58444102 0.59244476 0.32952266 0.87903224
  0.40938244 0.67340265 0.33367091 0.0698992 ]
 [0.88035739 0.4264009  0.74902234 0.45333326 0.91937974 0.6552587
  0.85408029 0.49791898 0.02036147 0.25036213]
 [0.62568255 0.71032738 0.78343014 0.56903372 0.07844213 0.64061568
  0.23110907 0.63243707 0.47909875 0.04872689]
 [0.56621226 0.09292283 0.3827601  0.83566685 0.38180909 0.8622741
  0.24701286 0.90335492 0.62365637 0.49063807]
 [0.14959043 0.12654561 0.26734348 0.66404263 0.7398541  0.77924935
  0.59004589 0.6864495  0.25357072 0.50725663]
 [0.39735026 0.12725633 0.75905623 0.77341054 0.40611937 0.72832665
  0.91109469 0.43806895 0.06579028 0.30637576]
 [0.60066043 0.50629856 0.47839571 0.37404341 0.59841506 0.0263607
  0.93439312 0.18511153 0.78158934 0.30159292]
 [0.92723715 0.11152464 0.27500812 0.02854643 0.63567256 0.0796254

13. Solve the system of equations:

  $3x - 11y = 3$

  $x - 4y = 6$

  using `numpy.linalg.solve`

In [34]:
a = np.array([[3, -11], [1, -4]])
b = np.array([3,6])
outcome = np.linalg.solve(a,b)
print("x and y are: ", outcome[0], outcome[1])

x and y are:  -53.99999999999997 -14.999999999999993
